export const LAY_DANH_MUC_KHOA_HOC  = 'LAY_DANH_MUC_KHOA_HOC';
export const LAY_DANH_SACH_KHOA_HOC = 'LAY_DANH_SACH_KHOA_HOC';
export const THEM_KHOA_HOC = 'THEM_KHOA_HOC ';
export const SUA_KHOA_HOC = 'SUA_KHOA_HOC ';
export const XOA_KHOA_HOC = 'XOA_KHOA_HOC ';
export const LAY_HINH_ANH_KHOA_HOC = ' LAY_HINH_ANH_KHOA_HOC';